### PR TITLE
Use floating/popup window to display commit

### PR DESCRIPTION
**Pull request by voldikss**
Since coc-git can show commits in floating window, I can remove the plugin https://github.com/rhysd/git-messenger.vim.

related: #91

### CODE REVIEW

**Comment by chemzqm** [comment]
No, it's break change and I would like to use split window and fugitive for commit.

**Comment by voldikss** [comment]
Could we make a configuration to allow to open commit in the floating window?

**Comment by voldikss** [comment]
Or add an optional value `floating` to `git.splitWindowCommand` to use floating window

**Comment by chemzqm** [comment]
> Could we make a configuration to allow to open commit in the floating window?

Yes, consider send PR for it.

**Comment by voldikss** [comment]
Could we rename `git.splitWindowCommand`(e.g. `git.showCommit.strategy` which accepts `floating`, `sp`, `above sp`, etc.) or just add another configuration option?

**Comment by chemzqm** [comment]
I prefer use another configuration option

**Pull request closed without merging**
